name: CI
on:
  push:
    branches:
      - 'vi-translation'
  pull_request:
    branches:
      - 'vi-translation'

jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: 'vi-translation'
      - name: Update rustup
        run: rustup self update
      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install nightly -c rust-docs
          rustup override set nightly
      - name: Install mdbook
        run: |
          mkdir bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.5/mdbook-v0.4.5-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
          echo "$(pwd)/bin" >> ${GITHUB_PATH}
      - name: Report versions
        run: |
          rustup --version
          rustc -Vv
          mdbook --version
      - name: Lint for local file paths
        run: |
          mdbook test
          mdbook build
      - name: Publish Book Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/book
          name: rust-lang-vi

